### ISSUE TITLE
why not GPU?

### ISSUE THREAD

**Issue by kingaza** [MrEliptik/HandPose#12]
amazing work~

I supposed it could do inference faster if I use tensorflow-gpu, but failed.
The error shows:
===========================================
(handpose) D:\1_Dev\HandPose>python HandPose.py
Traceback (most recent call last):
  File "C:\Users\kinga\Anaconda3\envs\handpose\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\kinga\Anaconda3\envs\handpose\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\kinga\Anaconda3\envs\handpose\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\kinga\Anaconda3\envs\handpose\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\kinga\Anaconda3\envs\handpose\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "HandPose.py", line 1, in <module>
    from utils import detector_utils as detector_utils
  File "D:\1_Dev\HandPose\utils\detector_utils.py", line 4, in <module>
    import tensorflow as tf
  File "C:\Users\kinga\Anaconda3\envs\handpose\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\kinga\Anaconda3\envs\handpose\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\kinga\Anaconda3\envs\handpose\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\kinga\Anaconda3\envs\handpose\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\kinga\Anaconda3\envs\handpose\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\kinga\Anaconda3\envs\handpose\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\kinga\Anaconda3\envs\handpose\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\kinga\Anaconda3\envs\handpose\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: 找不到指定的模块。

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by MrEliptik** [comment]
Thank you for your message. Originally, my end goal was to make it usable on embedded device, with a minimal footprint. Therefore, using the GPU was not my goal. 

What did you try exactly ?

**Comment by kingaza** [comment]
Hi, I am make a prototype of gesture control for medical device, e.g. in operation room. Therefore your project help me a lot, because it save me too much time and effort. Thanks again.
Actually I have not decided CPU or GPU. Of course, multiprocessing is also a good choice. So, I think I can close this issue.

**Comment by MrEliptik** [comment]
Super interesting, and I'm glad this project can help you. In case you decide to go with GPU and you have to make some changes, don't hesitate to open a pull request! Also, if you decide to share your progress on your project, please write to me as I find it very interesting. Good luck.
